platform :ios, '9.0'

target 'CryptExUI' do
  use_frameworks!

  pod 'Cryptex', :path => '../'
  
  # To install all exchanges
  #pod 'Cryptex', '~> 0.0.4'

  # To install only one exchange
  #pod 'Cryptex/Gemini', '~> 0.0.4'

  # To install two or more exchanges
  #pod 'Cryptex', '~> 0.0.4', :subspecs => ['Gemini', 'GDAX', "Poloniex"]
end
